# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190126_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Gender'),
        ),
    ]
